name: driver_customer_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  adaptive_theme: ^3.1.1
  auto_size_text: ^3.0.0
  avatar_glow: ^2.0.2
  awesome_notifications: ^0.8.2
  brasil_fields: ^1.14.0
  bubble: ^1.2.1
  cached_network_image: ^3.2.1
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.0+1
  firebase_analytics: ^9.1.6
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.4
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.5
  flutter_launcher_icons: ^0.9.2
  flutter_localization: ^0.1.14
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  flutter_secure_storage: ^5.0.2
  flutter_stripe: ^4.0.0
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.0.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.1.0
  global_configuration: ^2.0.0-nullsafety.1
  google_maps_flutter: ^2.1.12
  google_place: ^0.4.7
  google_sign_in: ^5.4.0
  image_picker: ^0.8.5+3
  intl: ^0.18.1
  loader_overlay: ^2.0.7
  location: ^4.4.0
  maps_launcher: ^2.0.1
  mime: ^1.0.2
  mvc_pattern: ^8.11.0
  permission_handler: ^10.0.0
  place_picker: ^0.9.19
  select_dialog: ^2.0.0
  sign_button: ^2.0.2
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.20
  validators: ^3.0.0
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo.png"
  remove_alpha_ios: true
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/cfg/
    - assets/img/

  generate: true

  uses-material-design: true

  fonts:
    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf
    - family: Uber
      fonts:
        - asset: assets/fonts/ClanOT-Medium.ttf
        - asset: assets/fonts/ClanOT-Bold.ttf
          weight: 700
